version: "3"
services:
    nginx:
      container_name: orbis-training-docker
      image: marlonric/orbis-training-docker:2.0.0
      ports:
        - "3030:1042"
        - "35729:35729"
      volumes:
        - $PWD/app:/app
      working_dir: /app
      command: ["npm", "start"]
    test:
      image: node:10.10.0-slim
      container_name: node-slim
      command: ["curl", "http://orbis-training-docker:1042"]